spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comparador
    username: comparador_user
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

affiliates:
  aliexpress:
    apiUrl: https://api.aliexpress.com/products
    apiKey: TU_API_KEY